apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: database
    {{- include "get-cookin.labels" . | nindent 4 }}
data:
  postgresql.conf: |
{{ .Files.Get "files/postgresql.conf" | nindent 4 }}
  pg_hba.conf: |
{{ .Files.Get "files/pg_hba.conf" | nindent 4 }}
